default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo +stable fmt --all -- --check
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: cargo-dev
        name: cargo dev
        entry: bash -lc 'if [ -f "$HOME/export-esp.sh" ]; then . "$HOME/export-esp.sh"; fi; cargo dev'
        language: system
        pass_filenames: false
        stages: [pre-push]

  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.3.0
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]
