[package]
edition = "2024"
name = "smart-glove"
rust-version = "1.93"
version = "0.1.0"

[workspace]
members = ["xtask"]
resolver = "2"

[[bin]]
name = "smart-glove"
path = "./src/bin/main.rs"
test = false

[dependencies]
defmt = "0.3"

[target.'cfg(all(target_arch = "xtensa", target_os = "none"))'.dependencies]
critical-section = "1.2.0"
esp-bootloader-esp-idf = { version = "0.4.0", features = ["esp32s3"] }
esp-hal = { version = "~1.0", features = ["esp32s3"] }
esp-println = { version = "0.16.1", features = ["esp32s3", "defmt-espflash"] }


[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1     # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false
