[package]
name = "smart-glove"
version = "0.1.0"
authors = ["Finn Sheng <yupbrokendream@gmail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.82"

[[bin]]
name = "identity_probe"
path = "src/bin/identity_probe.rs"
harness = false # do not use the built-in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice, and they don't increase the size on Flash
opt-level = "z"
[patch.crates-io]
esp-idf-sys = { git = "https://github.com/esp-rs/esp-idf-sys.git" }
esp-idf-hal = { git = "https://github.com/esp-rs/esp-idf-hal.git" }
esp-idf-svc = { git = "https://github.com/esp-rs/esp-idf-svc.git" }

[dependencies]
log = "0.4"
embedded-svc = "0.29"
esp-idf-svc = { version = "0.52.1", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }
# Remove `generic-queue-8` if you plan to use `embassy-time` WITH `embassy-executor`
embassy-time = { version = "0.5", features = ["generic-queue-8"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[[package.metadata.esp-idf-sys.extra_components]]
component_dirs = ["src/experiment/components"]
bindings_header = "src/experiment/espdl_bindings.h"
bindings_module = "espdl_experiment"

[build-dependencies]
embuild = "0.33"
