[package]
name = "smart-glove"
version = "0.1.0"
authors = ["Finn Sheng <yupbrokendream@gmail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.82"

[workspace]
members = ["src/provision", "src/drivers", "src/identity"]

[[bin]]
name = "smart-glove"
harness = false # do not use the built-in cargo test harness -> resolve rust-analyzer errors

[[bin]]
name = "provision"
path = "src/bin/provision.rs"
harness = false

[[bin]]
name = "identity"
path = "src/bin/identity.rs"
harness = false

[[bin]]
name = "driver"
path = "src/bin/driver.rs"
harness = false

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice, and they don't increase the size on Flash
opt-level = "z"
[patch.crates-io]
esp-idf-sys = { git = "https://github.com/esp-rs/esp-idf-sys.git" }
esp-idf-hal = { git = "https://github.com/esp-rs/esp-idf-hal.git" }
esp-idf-svc = { git = "https://github.com/esp-rs/esp-idf-svc.git" }

[dependencies]
log = "0.4"
esp-idf-svc = { version = "0.52.1", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }
# Remove `generic-queue-8` if you plan to use `embassy-time` WITH `embassy-executor`
embassy-time = { version = "0.5", features = ["generic-queue-8"] }
identity = { path = "src/identity" }
provision = { path = "src/provision" }
drivers = { path = "src/drivers" }

[[package.metadata.esp-idf-sys.extra_components]]
component_dirs = ["src/experiment/components"]
bindings_header = "src/experiment/espdl_bindings.h"
bindings_module = "espdl_experiment"

[build-dependencies]
embuild = "0.33"
