[alias]
dev = "run --manifest-path xtask/Cargo.toml --target aarch64-apple-darwin -- dev"

[target.xtensa-esp32s3-none-elf]
linker = "./scripts/xtensa-esp32s3-elf-gcc"
runner = "espflash flash --monitor --chip esp32s3"

[env]
ESP_LOG = "debug" # log level

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["core"]
